### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by gdedi001** [naralynne/naralynne-TeaCozy#4]
_Grade: Satisfactory_

Fantastic job on your project! You were able to utilize `<div>` tags correctly, and your final submission mimics the design spec to a tee. In addition to this, you properly implemented the `<footer>` tag to reflect the footer area of your site. An area for improvement here is with your usage of the `class` attribute. 

A recommendation here is to check out the article and make the appropriate changes .
https://css-tricks.com/the-difference-between-id-and-class/

**Comment by naralynne** [comment]
Thank you so much! The article was helpful :)
